services:
  - type: web
    name: fitbond-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn habit.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: habit.settings
