### register
POST http://127.0.0.1:8000/account/register/
Content-Type: application/json

{
    "email": "farhang1@example.com",
    "password1": "farhang1234",
    "password2": "farhang1234"
}

### login
POST http://localhost:8000/api/account/
Content-Type: application/json

{
    "email": "mehrnoosh@example.com",
    "password": "mehrnoosh1234"
}

### logs_create
POST http://localhost:8000/habit/logs/create/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4MDEyODcxLCJpYXQiOjE3NDgwMDkyNzEsImp0aSI6IjNhNGZiMTI3MDYwZDQ4ZTlhNjFiOGY3OTQ3NTU1ODJkIiwidXNlcl9pZCI6ImU1NzhkZGUzLTE4OGQtNDVhMC1hMGQ5LWUxZDM3ODE3NDYyYiJ9.IKXH6qJ5Vy9Q7i1uIPsxFSem8icoUS0q_WnFoDRGN-s

{
    "walking_steps": 6000,
    "exercise_minutes": 20,
    "exercise_description": "Yoga"
}

### get_token
POST http://localhost:8000/account/token/
Content-Type: application/json

{
  "email": "mehrnoosh@example.com",
  "password": "mehrnoosh1234"
}

### create_group
POST http://localhost:8000/habit/groups/create/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3MTM3ODQ5LCJpYXQiOjE3NDcxMzQyNDksImp0aSI6IjRjMjY5ODQwYmY3ZjRlZGNiZDRkMWZmNjYzNDQzZTMwIiwidXNlcl9pZCI6IjFjNmViNjE5LTI0MzctNDMyMS1iN2ZmLWZhM2U3ZDEyODgzNiJ9.-cHgAC-QVxizwijKQAqcRjoh8T2TbfQloA5N581Iqhk

{
    "name": "Decipline",
    "member_ids": [3, 4, 5]
}