# Generated by Django 5.2 on 2025-05-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0003_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='habit',
            name='exercise_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='exercise_minutes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='habit',
            name='walking_steps',
            field=models.IntegerField(),
        ),
    ]
