# Generated by Django 5.2 on 2025-06-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0004_rename_date_habit_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='exercise_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='exercise_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='log',
            name='walking_steps',
            field=models.IntegerField(default=0),
        ),
    ]
