# Generated by Django 5.2 on 2025-06-01 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0005_log_exercise_description_log_exercise_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='steps',
        ),
    ]
