# Generated by Django 5.2 on 2025-06-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0006_remove_log_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='exercise_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='habit',
            name='walking_steps',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
